import type { MapNativeCandidate } from "./mapNativeDesigner";
import { haversineMeters } from "./haversine";
import type { RouteLineString } from "./routeTypes";

/**
 * Hand-curated East Village gas logo (~10 km). Grid corners only — no Mapbox snap.
 * Generated by scripts/render-gas-logo-route.mjs (pump + hose + headphone person).
 */
export const CURATED_GAS_LOGO_MANHATTAN_COORDS: [number, number][] = [
  [40.7303056, -74.0041359],
  [40.7369856, -74.0014408],
  [40.735227, -73.99385],
  [40.7342992, -73.9942243],
  [40.734918, -73.9968951],
  [40.7345923, -73.9954894],
  [40.735118, -73.9952773],
  [40.7354437, -73.996683],
  [40.734918, -73.9968951],
  [40.7342992, -73.9942243],
  [40.7285469, -73.996545],
  [40.7303056, -74.0041359],
  [40.7336456, -74.0027883],
  [40.7318869, -73.9951975],
  [40.731431, -73.9932295],
  [40.7296991, -73.9939282],
  [40.7291781, -73.9916791],
  [40.7317759, -73.990631],
  [40.7309291, -73.9869762],
  [40.7329765, -73.9838445],
  [40.7328542, -73.981127],
  [40.7318041, -73.9787839],
  [40.7312751, -73.9786899],
  [40.7319784, -73.9805581],
  [40.7326331, -73.9836756],
  [40.731679, -73.9816012],
  [40.7291431, -73.9826243],
  [40.7261662, -73.9859773],
  [40.7291431, -73.9826243],
  [40.7252543, -73.9820413],
  [40.7291431, -73.9826243],
  [40.7308634, -73.9808542],
  [40.7317666, -73.9781842],
];

export const CURATED_GAS_LOGO_DESIGN_INTENT =
  "Curated GAS logo Manhattan v1: blocky pump with display window, hose loop, headphone person, raised nozzle arm. Features: pump, window, hose loop, headphones, person, body, legs, nozzle.";

export function curatedGasLogoRouteKm(): number {
  let meters = 0;
  const coords = CURATED_GAS_LOGO_MANHATTAN_COORDS;
  for (let i = 1; i < coords.length; i++) {
    meters += haversineMeters(coords[i - 1]!, coords[i]!);
  }
  return meters / 1000;
}

export function curatedGasLogoMapNativeCandidate(): MapNativeCandidate {
  const anchors = CURATED_GAS_LOGO_MANHATTAN_COORDS;
  let minLat = Infinity;
  let maxLat = -Infinity;
  let minLng = Infinity;
  let maxLng = -Infinity;
  for (const [lat, lng] of anchors) {
    minLat = Math.min(minLat, lat);
    maxLat = Math.max(maxLat, lat);
    minLng = Math.min(minLng, lng);
    maxLng = Math.max(maxLng, lng);
  }
  return {
    placement: {
      center: [(minLat + maxLat) / 2, (minLng + maxLng) / 2],
      rotationDeg: 29,
      scale: 1,
    },
    anchors,
    km: curatedGasLogoRouteKm(),
    designIntent: CURATED_GAS_LOGO_DESIGN_INTENT,
    kind: "street-design",
    routeMode: "direct-grid",
  };
}

export function curatedGasLogoRouteLine(): RouteLineString {
  const coords = CURATED_GAS_LOGO_MANHATTAN_COORDS;
  return {
    coordinates: coords,
    distanceMeters: curatedGasLogoRouteKm() * 1000,
    blockWaypoints: coords,
  };
}
