import type { MapNativeCandidate } from "./mapNativeDesigner";
import { haversineMeters } from "./haversine";
import type { RouteLineString } from "./routeTypes";

/**
 * Verified crown route compiled onto the Manhattan street lattice.
 * Source proof: tmp-independent-lattice-icon-proof/classic.gpx, generated by
 * scripts/tmp-independent-lattice-icon-proof.mjs with zero skipped lattice pins.
 */
export const CURATED_CROWN_MANHATTAN_COORDS: [number, number][] = [
  [40.7434700, -74.0072380],
  [40.7422890, -74.0044320],
  [40.7421250, -74.0045540],
  [40.7422890, -74.0044320],
  [40.7410800, -74.0015550],
  [40.7398810, -73.9987130],
  [40.7386860, -73.9958740],
  [40.7373310, -73.9926540],
  [40.7379240, -73.9922480],
  [40.7385110, -73.9918060],
  [40.7390980, -73.9913880],
  [40.7396760, -73.9909610],
  [40.7410310, -73.9941670],
  [40.7416290, -73.9937320],
  [40.7422330, -73.9932920],
  [40.7429100, -73.9927980],
  [40.7435680, -73.9923180],
  [40.7441860, -73.9918710],
  [40.7448190, -73.9914090],
  [40.7454210, -73.9909680],
  [40.7460380, -73.9905180],
  [40.7466660, -73.9900680],
  [40.7472770, -73.9896170],
  [40.7467960, -73.9884730],
  [40.7475460, -73.9883330],
  [40.7478960, -73.9891570],
  [40.7472770, -73.9896170],
  [40.7466660, -73.9900680],
  [40.7460380, -73.9905180],
  [40.7454210, -73.9909680],
  [40.7448190, -73.9914090],
  [40.7460180, -73.9942530],
  [40.7453830, -73.9947090],
  [40.7447650, -73.9951590],
  [40.7453830, -73.9947090],
  [40.7460180, -73.9942530],
  [40.7466180, -73.9938130],
  [40.7472360, -73.9933620],
  [40.7478630, -73.9929050],
  [40.7484690, -73.9924630],
  [40.7491010, -73.9920060],
  [40.7497060, -73.9915630],
  [40.7491010, -73.9920060],
  [40.7484690, -73.9924630],
  [40.7496740, -73.9952960],
  [40.7490560, -73.9957290],
  [40.7484350, -73.9961920],
  [40.7478360, -73.9966340],
  [40.7472170, -73.9970850],
  [40.7465800, -73.9975500],
  [40.7459650, -73.9979900],
  [40.7465800, -73.9975500],
  [40.7472170, -73.9970850],
  [40.7478360, -73.9966340],
  [40.7484350, -73.9961920],
  [40.7493380, -73.9973650],
  [40.7496590, -73.9990650],
  [40.7496000, -73.9991070],
  [40.7495500, -73.9989860],
  [40.7496000, -73.9991070],
  [40.7496590, -73.9990650],
  [40.7502750, -73.9986120],
  [40.7509070, -73.9981550],
  [40.7515070, -73.9977250],
  [40.7509070, -73.9981550],
  [40.7502750, -73.9986120],
  [40.7496590, -73.9990650],
  [40.7496000, -73.9991070],
  [40.7495500, -73.9989860],
  [40.7496000, -73.9991070],
  [40.7484300, -73.9999570],
  [40.7477910, -74.0004220],
  [40.7471710, -74.0008680],
  [40.7465210, -74.0013500],
  [40.7458550, -74.0018590],
  [40.7452350, -74.0022970],
  [40.7446390, -74.0027320],
  [40.7458170, -74.0055340],
  [40.7452310, -74.0059600],
  [40.7446460, -74.0063850],
  [40.7440610, -74.0068110],
  [40.7434700, -74.0072380],
  [40.7422890, -74.0044320],
  [40.7428830, -74.0039990],
  [40.7416740, -74.0011230],
  [40.7404700, -73.9982870],
  [40.7392720, -73.9954460],
  [40.7398600, -73.9950180],
  [40.7404420, -73.9945930],
  [40.7416420, -73.9974340],
  [40.7428470, -74.0002680],
  [40.7440560, -74.0031550],
  [40.7434760, -74.0035810],
  [40.7428830, -74.0039990],
];

export const CURATED_CROWN_DESIGN_INTENT =
  "Verified crown Manhattan v1: street-lattice crown with base band, three tall points, side shoulders, and rectangular jewel band.";

export function curatedCrownRouteKm(): number {
  let meters = 0;
  const coords = CURATED_CROWN_MANHATTAN_COORDS;
  for (let i = 1; i < coords.length; i++) {
    meters += haversineMeters(coords[i - 1]!, coords[i]!);
  }
  return meters / 1000;
}

export function curatedCrownManhattanMapNativeCandidate(): MapNativeCandidate {
  const anchors = CURATED_CROWN_MANHATTAN_COORDS;
  let minLat = Infinity;
  let maxLat = -Infinity;
  let minLng = Infinity;
  let maxLng = -Infinity;
  for (const [lat, lng] of anchors) {
    minLat = Math.min(minLat, lat);
    maxLat = Math.max(maxLat, lat);
    minLng = Math.min(minLng, lng);
    maxLng = Math.max(maxLng, lng);
  }
  return {
    placement: {
      center: [(minLat + maxLat) / 2, (minLng + maxLng) / 2],
      rotationDeg: 29,
      scale: 1,
    },
    anchors,
    km: curatedCrownRouteKm(),
    designIntent: CURATED_CROWN_DESIGN_INTENT,
    kind: "street-design",
    routeMode: "direct-grid",
  };
}

export function curatedCrownRouteLine(): RouteLineString {
  const coords = CURATED_CROWN_MANHATTAN_COORDS;
  return {
    coordinates: coords,
    distanceMeters: curatedCrownRouteKm() * 1000,
    blockWaypoints: coords,
  };
}
