import type { MapNativeCandidate } from "./mapNativeDesigner";
import { haversineMeters } from "./haversine";
import type { RouteLineString } from "./routeTypes";

/**
 * Verified Manhattan Nike swoosh interpretation from tmp-interp-designs/nike.
 * Generated by scripts/interp-designs.ts through the production lattice compiler.
 */
export const CURATED_NIKE_SWOOSH_MANHATTAN_COORDS: [number, number][] = [
  [40.7502290, -74.0023140],
  [40.7496110, -74.0027750],
  [40.7489740, -74.0032360],
  [40.7483550, -74.0036840],
  [40.7477030, -74.0041640],
  [40.7470230, -74.0046530],
  [40.7458550, -74.0018590],
  [40.7452350, -74.0022970],
  [40.7446390, -74.0027320],
  [40.7440560, -74.0031550],
  [40.7428470, -74.0002680],
  [40.7422580, -74.0006950],
  [40.7410560, -73.9978620],
  [40.7398600, -73.9950180],
  [40.7404420, -73.9945930],
  [40.7390980, -73.9913880],
  [40.7396760, -73.9909610],
  [40.7391690, -73.9897510],
  [40.7383380, -73.9877780],
  [40.7389340, -73.9873430],
  [40.7388980, -73.9872590],
  [40.7395080, -73.9868120],
  [40.7388480, -73.9852450],
  [40.7395140, -73.9847520],
  [40.7401770, -73.9842670],
  [40.7395000, -73.9826690],
  [40.7401250, -73.9822170],
  [40.7407510, -73.9817650],
  [40.7397950, -73.9795310],
  [40.7404190, -73.9790880],
  [40.7410430, -73.9786420],
  [40.7416550, -73.9781700],
  [40.7422740, -73.9777200],
  [40.7428910, -73.9772760],
  [40.7435050, -73.9768230],
  [40.7441110, -73.9763850],
  [40.7430900, -73.9740140],
  [40.7437860, -73.9735080],
  [40.7444480, -73.9730270],
  [40.7437860, -73.9735080],
  [40.7430900, -73.9740140],
  [40.7441110, -73.9763850],
  [40.7435050, -73.9768230],
  [40.7428910, -73.9772760],
  [40.7422740, -73.9777200],
  [40.7416550, -73.9781700],
  [40.7410430, -73.9786420],
  [40.7419810, -73.9808710],
  [40.7413630, -73.9813210],
  [40.7407510, -73.9817650],
  [40.7414160, -73.9833670],
  [40.7408010, -73.9838160],
  [40.7401770, -73.9842670],
  [40.7408260, -73.9858270],
  [40.7408740, -73.9859400],
  [40.7402150, -73.9864100],
  [40.7408810, -73.9879850],
  [40.7413640, -73.9891380],
  [40.7406760, -73.9894220],
  [40.7406180, -73.9892450],
  [40.7406760, -73.9894220],
  [40.7407170, -73.9895260],
  [40.7406760, -73.9894220],
  [40.7406190, -73.9894420],
  [40.7408860, -73.9900830],
  [40.7402770, -73.9905250],
  [40.7416290, -73.9937320],
  [40.7428250, -73.9965700],
  [40.7440250, -73.9994130],
  [40.7446300, -73.9989690],
  [40.7453050, -73.9984720],
  [40.7465210, -74.0013500],
  [40.7471710, -74.0008680],
  [40.7477910, -74.0004220],
  [40.7484300, -73.9999570],
  [40.7488510, -74.0009740],
  [40.7496110, -74.0027750],
  [40.7502290, -74.0023140],
];

export const CURATED_NIKE_SWOOSH_DESIGN_INTENT =
  "Curated Nike swoosh Manhattan v1: closed tapered swoosh outline compiled to real street junctions. Features: broad heel, curved belly, tapered rising tip, ribbon outline.";

export function curatedNikeSwooshRouteKm(): number {
  let meters = 0;
  const coords = CURATED_NIKE_SWOOSH_MANHATTAN_COORDS;
  for (let i = 1; i < coords.length; i++) {
    meters += haversineMeters(coords[i - 1]!, coords[i]!);
  }
  return meters / 1000;
}

export function curatedNikeSwooshMapNativeCandidate(): MapNativeCandidate {
  const anchors = CURATED_NIKE_SWOOSH_MANHATTAN_COORDS;
  let minLat = Infinity;
  let maxLat = -Infinity;
  let minLng = Infinity;
  let maxLng = -Infinity;
  for (const [lat, lng] of anchors) {
    minLat = Math.min(minLat, lat);
    maxLat = Math.max(maxLat, lat);
    minLng = Math.min(minLng, lng);
    maxLng = Math.max(maxLng, lng);
  }
  return {
    placement: {
      center: [(minLat + maxLat) / 2, (minLng + maxLng) / 2],
      rotationDeg: 29,
      scale: 1,
    },
    anchors,
    km: curatedNikeSwooshRouteKm(),
    designIntent: CURATED_NIKE_SWOOSH_DESIGN_INTENT,
    kind: "street-design",
    routeMode: "direct-grid",
  };
}

export function curatedNikeSwooshRouteLine(): RouteLineString {
  const coords = CURATED_NIKE_SWOOSH_MANHATTAN_COORDS;
  return {
    coordinates: coords,
    distanceMeters: curatedNikeSwooshRouteKm() * 1000,
    blockWaypoints: coords,
  };
}
