import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const sharp = require("sharp");
const jiti = require("jiti")(import.meta.url);
const { prepareTracedBinaryComponents, centerlinePolylineFromPreparedBinary } = jiti("../lib/centerlineFromMask.ts");
const { buildGraph, meters } = jiti("./trace-contour.ts");
const root=process.cwd();
const outDir=path.join(root,'tmp-sneaker-hybrid',new Date().toISOString().replace(/[:.]/g,'-'));
const idx=(x,y,w)=>y*w+x;
const M_PER_LAT=111320; const PROJ={lat0:40.718,lng0:-74.002,mPerLng:M_PER_LAT*Math.cos(40.718*Math.PI/180)};
function routePixel(r,g,b){return r>=138&&g>=78&&g<=190&&b>=55&&b<=178&&r-g>=18&&g-b>=4&&r-b>=36;}
function llToLocal([lat,lng]){return [(lng-PROJ.lng0)*PROJ.mPerLng,(lat-PROJ.lat0)*M_PER_LAT];}
function pixelToLl([x,y],fit){const u=(x-fit.left)/(fit.right-fit.left),v=(y-fit.top)/(fit.bottom-fit.top);return [fit.north+(fit.south-fit.north)*v,fit.west+(fit.east-fit.west)*u];}
function neighbors8(x,y,w,h){const out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<w&&ny<h)out.push([nx,ny]);}return out;}
function components(mask,w,h){const seen=new Uint8Array(w*h),out=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const st=idx(x,y,w);if(!mask[st]||seen[st])continue;const stack=[[x,y]],pixels=[];seen[st]=1;let minX=x,minY=y,maxX=x,maxY=y;while(stack.length){const [cx,cy]=stack.pop();pixels.push([cx,cy]);minX=Math.min(minX,cx);minY=Math.min(minY,cy);maxX=Math.max(maxX,cx);maxY=Math.max(maxY,cy);for(const [nx,ny] of neighbors8(cx,cy,w,h)){const ni=idx(nx,ny,w);if(mask[ni]&&!seen[ni]){seen[ni]=1;stack.push([nx,ny]);}}}out.push({pixels,count:pixels.length,bbox:{minX,minY,maxX,maxY}});}return out.sort((a,b)=>b.count-a.count);}
function bounds(points){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return {minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};}
function dist(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1]);}
function simplify(points,minDist){const out=[];let last=null;for(const p of points){if(!last||dist(last,p)>=minDist){out.push(p);last=p;}}return out;}
function routeD(points,project){return points.map((p,i)=>{const [x,y]=project(p);return `${i?'L':'M'} ${x.toFixed(1)} ${y.toFixed(1)}`}).join(' ')}
async function extract(gap){const source=path.join(root,'sneaker.jpg');const {data,info}=await sharp(source).raw().toBuffer({resolveWithObject:true});const mask=new Uint8Array(info.width*info.height);for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const i=(y*info.width+x)*info.channels;if(routePixel(data[i],data[i+1],data[i+2]))mask[idx(x,y,info.width)]=1;}const kept=components(mask,info.width,info.height).filter(c=>((c.bbox.minY+c.bbox.maxY)/2)>info.height*.42&&c.count>=80).slice(0,4);const all=kept.flatMap(c=>c.pixels);const b=bounds(all),pad=8;const crop={minX:Math.max(0,b.minX-pad),minY:Math.max(0,b.minY-pad),maxX:Math.min(info.width-1,b.maxX+pad),maxY:Math.min(info.height-1,b.maxY+pad)};const cw=crop.maxX-crop.minX+1,ch=crop.maxY-crop.minY+1;const lineMask=new Uint8Array(cw*ch);for(const c of kept)for(const [x,y] of c.pixels)lineMask[idx(x-crop.minX,y-crop.minY,cw)]=255;return prepareTracedBinaryComponents(lineMask,cw,ch,gap,20).map((comp,i)=>({i,pts:(centerlinePolylineFromPreparedBinary(comp,cw,ch)||[]).map(([x,y])=>[x+crop.minX,y+crop.minY])})).filter(s=>s.pts.length>=2).sort((a,b)=>b.pts.length-a.pts.length).map(s=>({...s,pts:simplify(s.pts,2.2)}));}
function parseGpx(s){return [...s.matchAll(/lat="([^"]+)" lon="([^"]+)"/g)].map(m=>[+m[1],+m[2]]);}
function totalKm(chains){let m=0;for(const chain of chains)for(let i=1;i<chain.length;i++)m+=meters(chain[i-1],chain[i]);return m/1000;}
async function renderBlind(chains,file,label=''){const pts=chains.flat().map(llToLocal),b=bounds(pts),pad=90,w=900,h=560;const view={minX:b.minX-pad,maxX:b.maxX+pad,minY:b.minY-pad,maxY:b.maxY+pad};const scale=Math.min((w-50)/(view.maxX-view.minX),(h-50)/(view.maxY-view.minY));const usedW=(view.maxX-view.minX)*scale,usedH=(view.maxY-view.minY)*scale;const ox=(w-usedW)/2,oy=(h-usedH)/2;const project=([x,y])=>[ox+(x-view.minX)*scale,oy+(view.maxY-y)*scale];const paths=chains.map(c=>`<path d="${routeD(c.map(llToLocal),project)}" fill="none" stroke="#111" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>`).join('\n');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="100%" height="100%" fill="#fff"/>${paths}${label?`<text x="18" y="34" font-family="Arial" font-size="22" font-weight="700">${label}</text>`:''}</svg>`;await sharp(Buffer.from(svg)).png().toFile(file);}
async function renderMap(graph,chains,file,label){const pts=chains.flat().map(llToLocal),b=bounds(pts),pad=260,w=1200,h=820;const view={minX:b.minX-pad,maxX:b.maxX+pad,minY:b.minY-pad,maxY:b.maxY+pad};const scale=Math.min((w-70)/(view.maxX-view.minX),(h-70)/(view.maxY-view.minY));const usedW=(view.maxX-view.minX)*scale,usedH=(view.maxY-view.minY)*scale;const ox=(w-usedW)/2,oy=(h-usedH)/2;const project=([x,y])=>[ox+(x-view.minX)*scale,oy+(view.maxY-y)*scale];const inView=([x,y])=>x>=view.minX&&x<=view.maxX&&y>=view.minY&&y<=view.maxY;const streets=[],seen=new Set();for(const [from,entries] of graph.adj.entries())for(const e of entries){const key=from<e.to?`${from}:${e.to}`:`${e.to}:${from}`;if(seen.has(key))continue;seen.add(key);const a=llToLocal(graph.coord.get(from)),bb=llToLocal(graph.coord.get(e.to));if(!inView(a)&&!inView(bb))continue;streets.push(`<path d="${routeD([a,bb],project)}" fill="none" stroke="#d7d7d7" stroke-width="1.4"/>`);}const paths=chains.map(c=>{const d=routeD(c.map(llToLocal),project);return `<path d="${d}" fill="none" stroke="#111" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/><path d="${d}" fill="none" stroke="#ef1744" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>`;}).join('\n');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="100%" height="100%" fill="#f6f4ef"/><rect x="24" y="24" width="${w-48}" height="${h-48}" fill="#fff"/>${streets.join('\n')}${paths}<text x="34" y="50" font-family="Arial" font-size="22" font-weight="700">${label}</text></svg>`;await sharp(Buffer.from(svg)).png().toFile(file);}
function gpxMulti(name,chains){return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="PaceCasso hybrid sneaker" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>${name}</name>\n${chains.map(chain=>`<trkseg>\n${chain.map(([lat,lng])=>`<trkpt lat="${lat.toFixed(7)}" lon="${lng.toFixed(7)}"></trkpt>`).join('\n')}\n</trkseg>`).join('\n')}\n</trk></gpx>\n`;}
async function main(){await fs.mkdir(outDir,{recursive:true});const fit={left:0,right:390,top:198,bottom:457,north:40.7294,south:40.7098,west:-74.0107,east:-73.9807};const body=parseGpx(await fs.readFile(path.join(root,'tmp-sneaker-raw-georef','2026-07-18T16-58-51-087Z','compact-082','compact-082-raw.gpx'),'utf8'));const gap1=await extract(1);const lace=gap1[1].pts.map(p=>pixelToLl(p,fit));const chains=[body,lace];const graph=await buildGraph();const km=totalKm(chains);await renderBlind(chains,path.join(outDir,'hybrid-blind.png'));await renderMap(graph,chains,path.join(outDir,'hybrid-map.png'),`hybrid body+laces ${km.toFixed(1)}km / ${(km*.621371).toFixed(2)}mi`);await fs.writeFile(path.join(outDir,'hybrid.gpx'),gpxMulti('hybrid-sneaker',chains));await fs.writeFile(path.join(outDir,'summary.json'),JSON.stringify({km:+km.toFixed(2),miles:+(km*.621371).toFixed(2),segments:chains.map(c=>c.length),body:'gap6 compact-082 raw',lace:'gap1 component 1 compact-082'},null,2));console.log(path.relative(root,outDir));}
main().catch(e=>{console.error(e);process.exit(1)});